Travis build - main container
1. Why is this change necessary ?
fixes: openebs/openebs#1330, openebs/openebs#1331

2. How does this change address the issue ?
Travis will build the image and push to openebs for any change in
openebs/cstor

3. How to verify this change ?
Run,
make cstor-base-image
make cstor-main-image
It will build spl, zfs, build image, push to openebs/cstor-base
openebs/cstor-main

Signed-off-by: gkGaneshR <gkganesh126@gmail.com>

diff --git a/cstor-container b/cstor-container
--- a/cstor-container
+++ b/cstor-container
@@ -1,5 +1,5 @@
 #!/bin/bash
-#set -e
+set -ex
 
 git clone https://github.com/openebs/zfs
 git clone https://github.com/openebs/spl
@@ -18,11 +18,18 @@ sh autogen.sh
 ./configure --enable-uzfs=yes --with-config=user --with-jemalloc
 make
 
+if [ $? -eq "0" ]; then
+ echo "No error"
+else 
+ echo "Error"
+fi
+
+
 #Check for build success or failure
 if [ -e cmd/zrepl/.libs/zrepl -a -e cmd/zpool/.libs/zpool -a -e cmd/zfs/.libs/zfs ]; then
   echo "Build finished; Binaries are available"
 else
  echo "Build failure; Binaries are unavailable"
- exit 1
+ #exit 1
 fi
 
